//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostAndFound.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [Serializable]
    public partial class Find
    {
        public int id { get; set; }

        [Display(Name = "תת קטגוריה")]
        public virtual SubCategory subCategory { get; set; }

        [StringLength(maximumLength: 50, MinimumLength = 2, ErrorMessage = "הזן תאור בין 2-50 תווים")]
        [Required]
        [Display(Name = "תאור")]
        public string description { get; set; }

        [Display(Name = "תמונה")]
        public string picture { get; set; }

        [Display(Name = "היכן נמצא")]
        public virtual Location location { get; set; }

        [Display(Name = "תאריך מציאה")]
        public System.DateTime dateFound { get; set; }

        [Display(Name = "תאריך עברי")]
        public string hebrewDate { get; set; }

        [StringLength(maximumLength: 20)]
        [Display(Name = "הערות")]
        public string notes { get; set; }

        [Required]
        [Display(Name = "שם המוצא")]
        public string finderName { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{7,10}",
                    ErrorMessage = "הזן מספר טלפון תקין")]
        [Display(Name = "טלפון")]
        public string cellphone { get; set; }
       
        [Required]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$",
                    ErrorMessage = "הזן כתובת מייל תקינה")]
        [Display(Name = "כתובת מייל")]
        public string email { get; set; }

        public static Find convertArciveToFind(Archive arcive)
        {
            Find find = new Find();
            find.hebrewDate = arcive.hebrewDate;
            find.id = arcive.id;
            find.notes = arcive.notes;
            find.location = arcive.location;
            find.subCategory = arcive.subCategory;
            find.cellphone = arcive.cellphone;
            find.dateFound = arcive.dateFound;
            find.email = arcive.email1;
            find.finderName = arcive.finderName;
            find.picture = arcive.picture;
            
            return find;
        }
    }
}
