//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostAndFound.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [Serializable]
    public partial class Find
    {
       
        [Display(Name = "תת קטגוריה")]
       public int subCategoryId { get; set; }

        [StringLength(maximumLength: 50, MinimumLength = 2, ErrorMessage = "הכניסי תאור בין 2-50 תווים")]
        [Required]
        [Display(Name = "תאור")]
        public string description { get; set; }

        [Display(Name = "היכן נמצא")]
        public int? locationId { get; set; }
        [Display(Name = "תאריך")]
        public System.DateTime dateFound { get; set; }
       
        [StringLength(maximumLength: 20)]
        [Display(Name = "הערות")]
        public string notes { get; set; }
       
        [Required]
        [RegularExpression(@"[0-9]{7,10}",
                    ErrorMessage = "הקישי מספר טלפון תקין")]
        [Display(Name = "טלפון")]
        public string cellphone { get; set; }
        [RegularExpression(@"[0-9]{7,10}",
                    ErrorMessage = "הקישי מספר טלפון תקין")]
         [Display(Name = "טלפון נוסף")]
        public string tel2 { get; set; }
        public int id { get; set; }
        [Display(Name = "תאריך עברי")]
        public string hebrewDate { get; set; }
        [Required]
        [Display(Name = "שם המוצא")]
        public string name { get; set; }
    
        public virtual Location  location{ get; set; }
        public virtual SubCategory subCategory { get; set; }
    }
}
